#!/bin/sh -x

export PLATFORM_VERSION=11
export ANDROID_MAJOR_VERSION=r
export CROSS_COMPILE=../toolchains/aarch64-linux-android-4.9/bin/aarch64-linux-android-
export CC=../toolchains/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-16.04/bin/clang

make mrproper
touch .scmversion
#make ARCH=arm64 exynos9610-a51xx_defconfig
make ARCH=arm64 exynos9610-a51xx_caliban_defconfig
make ARCH=arm64 -j$(nproc)
