#!/bin/sh -x

export ANDROID_MAJOR_VERSION=q
export CROSS_COMPILE=../toolchains/aarch64-linux-android-4.9/bin/aarch64-linux-android-
export CC=../toolchains/clang+llvm-8.0.11/bin/clang

make mrproper
#make ARCH=arm64 exynos9610-a51xx_defconfig
make ARCH=arm64 exynos9610-a51xx_caliban_defconfig
make ARCH=arm64 -j$(nproc)
